// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"database/sql/driver"
	"fmt"
	"time"
)

type Currency string

const (
	CurrencyUSD Currency = "USD"
	CurrencyEUR Currency = "EUR"
	CurrencyJPY Currency = "JPY"
)

func (e *Currency) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Currency(s)
	case string:
		*e = Currency(s)
	default:
		return fmt.Errorf("unsupported scan type for Currency: %T", src)
	}
	return nil
}

type NullCurrency struct {
	Currency Currency
	Valid    bool // Valid is true if Currency is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCurrency) Scan(value interface{}) error {
	if value == nil {
		ns.Currency, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Currency.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCurrency) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Currency), nil
}

type Account struct {
	ID        int64     `db:"id"`
	Owner     string    `db:"owner"`
	Balance   int32     `db:"balance"`
	Currency  Currency  `db:"currency"`
	CreatedAt time.Time `db:"created_at"`
}

type Entry struct {
	ID        int64 `db:"id"`
	AccountID int64 `db:"account_id"`
	// can be negative or positive
	Amount    int32     `db:"amount"`
	CreatedAt time.Time `db:"created_at"`
}

type Transfer struct {
	ID            int64 `db:"id"`
	FromAccountID int64 `db:"from_account_id"`
	ToAccountID   int64 `db:"to_account_id"`
	// must be positive
	Amount    int32     `db:"amount"`
	CreatedAt time.Time `db:"created_at"`
}
